version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-knowledge-qa-web:latest
    container_name: rag-knowledge-qa-web-container
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge